### ISSUE TITLE
arr - ? Are you a tiger??? must be "array"

### ISSUE THREAD

**Issue by DanielOrDany** [IMykolaI/into_the_speciality_mykola#4]
https://github.com/IMykolaI/into_the_speciality_mykola/blob/a11db444e2b16708538d14ea54a7c7747649188e/Lab4_Motychak.c.cpp#L19

**Comment by IMykolaI** [comment]
Fixed!

**Comment by IMykolaI** [comment]
> [into_the_speciality_mykola/Lab4_Motychak.c.cpp](https://github.com/IMykolaI/into_the_speciality_mykola/blob/a11db444e2b16708538d14ea54a7c7747649188e/Lab4_Motychak.c.cpp#L19)
> 
> Line 19 in [a11db44](/IMykolaI/into_the_speciality_mykola/commit/a11db444e2b16708538d14ea54a7c7747649188e)
> 
>  static int arr[n][n];
